### ISSUE TITLE
Got error when install package ag

### ISSUE THREAD

**Issue by ConnorWeng** [AnthonyMastrean/chocolateypackages#105]
Hi, I got error below:

ag v0.18.1
ag not installed. An error occurred during installation:
Object reference not set to an instance of an object.
The upgrade of ag was NOT successful.
ag not installed. An error occurred during installation:
Object reference not set to an instance of an object.

Any idea?
Please help.

**Comment by AnthonyMastrean** [comment]
Hm. It's not clear what that error is about. The install script couldn't be easier... might be something on the network didn't return and some value internal to Chocolatey is breaking? I pushed a new version anyway, updated the install script style.

Tested on my machine and it works :)

https://chocolatey.org/packages/ag/0.18.1.1129

**Comment by AnthonyMastrean** [comment]
8d904ab55681bd3a33d4e01f0b84d7c81ae9ad2a
