### ISSUE TITLE
Clink v0.4.4

### ISSUE THREAD

**Issue by piotr-cz** [AnthonyMastrean/chocolateypackages#129]
There is a new Clink version [v0.4.4](https://github.com/mridgers/clink/releases) available

**Comment by AnthonyMastrean** [comment]
https://chocolatey.org/packages/clink/0.4.4

**Comment by piotr-cz** [comment]
when running `cup`, choco says:

_clink.portable was not found with the source(s) listed._

If this is intended, should I uninstall _clink.portable_ and install _clink_ instead?

**Comment by AnthonyMastrean** [comment]
Oh no... were you using clink.portable? I don't have an enormous amount of
time to support all of the package variations, so I only uploaded the
installer version.

**Comment by piotr-cz** [comment]
Seems that _clink.portable_ [has disappeared](https://chocolatey.org/packages?q=clink.portable) from chocolatey database listings.

**Comment by AnthonyMastrean** [comment]
It's still there, just unlisted.

https://chocolatey.org/packages/clink.portable

To better manage my time, I thought I'd only maintain the installer-based
packages. Are you able to use clink instead of clink.portable?

**Comment by piotr-cz** [comment]
I'm using _Clink.portable_ as a drop-in for [ConEmu](https://conemu.github.io/) (using symlink).

I think I can use the installer-based package, as long as the autorun option is off.

**Comment by AnthonyMastrean** [comment]
I think the installer version registers itself as a cmd.exe pre-processor.
Is that what you're referring to as "autorun"?
