### ISSUE TITLE
choco install visualcplusplusruntime2008 doesn't work

### ISSUE THREAD

**Issue by AnthonyMastrean** [AnthonyMastrean/chocolateypackages#134]
User Vaquero <haag.olaf@gmail.com> sends the following message to the maintainers of Package 'visualcplusplusruntime2008'.

Hey Anthony!
choco install visualcplusplusruntime2008 -version 9.0.21022.8
doesn't work. (https://chocolatey.org/packages/visualcplusplusruntime2008)
I need that as a dependency for a package I'm creating.

Package Url: http://chocolatey.org/packages/visualcplusplusruntime2008

Pro-tip: It is recommended to (also) post your answer to the visualcplusplusruntime2008 comment section so that the information is publicly available.
This can prevent you from receiving the same question from multiple users.

Package comments: http://chocolatey.org/packages/visualcplusplusruntime2008#disqus

**Comment by Vaquero84** [comment]
Is there a way to merge this package with this one https://chocolatey.org/packages/vcredist2008 and add the version 9.0.21022.8 to it?

**Comment by AnthonyMastrean** [comment]
I'll look into it!

**Comment by AnthonyMastrean** [comment]
Looks like I unlisted that package a while ago (I forget why) and removed it from my repository. I don't use it professionally anymore. It's unlikely that I'll pick it back up. I can make you a maintainer and you can publish an update.

Or, make it an internal part of your package by firing off another Install-ChocolateyPackage call.
