### ISSUE TITLE
Haskell Platform considered harmful

### ISSUE THREAD

**Issue by AnthonyMastrean** [AnthonyMastrean/chocolateypackages#145]
> ‏bitemyapp
> Haskell Platform as the default recommendation considered harmful

https://twitter.com/bitemyapp/status/645827318376587264

Apparently, we should use minghc or stack.

https://github.com/fpco/minghc#using-the-installer
https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md

A package exists that needs some help/moderation.

https://chocolatey.org/packages/ghc

**Comment by bitemyapp** [comment]
>Apparently, we should use minghc or stack.

Yep.

**Comment by ndmitchell** [comment]
MinGHC has been discontinued. The platform remains harmful for the moment. I think Stack is the only reasonable choice.

**Comment by bitemyapp** [comment]
Seconding @ndmitchell here.

**Comment by snoyberg** [comment]
I'm also on board with @ndmitchell and @bitemyapp here.

**Comment by AnthonyMastrean** [comment]
Hehe, I was just interested in getting shellcheck running on Windows... not really into the Haskell ecosystem yet, but I appreciate the engagement! If I get moving on this, I'll reach out :)

**Comment by AnthonyMastrean** [comment]
I'll checkout Stack if the precompiled Windows binary doesn't work out.

https://chocolatey.org/packages/haskell-stack
