### ISSUE TITLE
Error during 'choco install Handbrake.install'

### ISSUE THREAD

**Issue by innovTech** [AnthonyMastrean/chocolateypackages#155]
On windows 7 Pro 64bits PC, some other installation packages work fine. 
But error appear during handbrake.install installation:

C:\Users\administrateur>choco install -v handbrake
Installing the following packages:
handbrake
By installing you accept licenses for the packages.

handbrake.install v0.10.1
The package handbrake.install wants to run 'chocolateyInstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider setting
 'allowGlobalConfirmation'. Run 'choco feature -h' for more details.
Do you want to run the script?
 1) yes
 2) no
 3) print
1
 COMMENTAIRES : Exporting function 'Get-BinRoot'.
 COMMENTAIRES : Exporting function 'Get-ChecksumValid'.
 COMMENTAIRES : Exporting function 'Get-ChocolateyUnzip'.
 COMMENTAIRES : Exporting function 'Get-ChocolateyWebFile'.
 COMMENTAIRES : Exporting function 'Get-EnvironmentVariable'.
 COMMENTAIRES : Exporting function 'Get-EnvironmentVariableNames'.
 COMMENTAIRES : Exporting function 'Get-FtpFile'.
 COMMENTAIRES : Exporting function 'Get-ProcessorBits'.
 COMMENTAIRES : Exporting function 'Get-UACEnabled'.
 COMMENTAIRES : Exporting function 'Get-VirusCheckValid'.
 COMMENTAIRES : Exporting function 'Get-WebFile'.
 COMMENTAIRES : Exporting function 'Get-WebHeaders'.
 COMMENTAIRES : Exporting function 'Install-BinFile'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyDesktopLink'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyEnvironmentVariable'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyExplorerMenuItem'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyFileAssociation'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyInstallPackage'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyPackage'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyPath'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyPinnedTaskBarItem'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyPowershellCommand'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyShortcut'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyVsixPackage'.
 COMMENTAIRES : Exporting function 'Install-Vsix'.
 COMMENTAIRES : Exporting function 'Install-ChocolateyZipPackage'.
 COMMENTAIRES : Exporting function 'Set-EnvironmentVariable'.
 COMMENTAIRES : Exporting function 'Start-ChocolateyProcessAsAdmin'.
 COMMENTAIRES : Exporting function 'Test-ProcessAdminRights'.
 COMMENTAIRES : Exporting function 'Uninstall-BinFile'.
 COMMENTAIRES : Exporting function 'Uninstall-ChocolateyPackage'.
 COMMENTAIRES : Exporting function 'UnInstall-ChocolateyZipPackage'.
 COMMENTAIRES : Exporting function 'Update-SessionEnvironment'.
 COMMENTAIRES : Exporting function 'Write-ChocolateyFailure'.
 COMMENTAIRES : Exporting function 'Write-ChocolateySuccess'.
 COMMENTAIRES : Exporting function 'Write-FileUpdateLog'.
 COMMENTAIRES : Exporting alias 'Generate-BinFile'.
 COMMENTAIRES : Exporting alias 'Add-BinFile'.
 COMMENTAIRES : Exporting alias 'Remove-BinFile'.
 Exception calling "GetResponse" with "0" argument(s): "The underlying connection was closed: An une

 xpected error occurred on a send."
 Au niveau de C:\ProgramData\chocolatey\helpers\functions\Get-WebHeaders.ps1 : 92 Caractère : 37
 +     $response = $request.GetResponse <<<< ();
     + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
     + FullyQualifiedErrorId : DotNetMethodException
The install of handbrake.install was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\handbrake.install\tools\chocolateyInstall.ps1'.
 See log for details.

handbrake v0.10
 The install of handbrake was successful.

Chocolatey installed 1/2 package(s). 1 package(s) failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures:
 - handbrake.install

**Comment by AnthonyMastrean** [comment]
Looks like the Handbrake team broke another download URL. 

https://handbrake.fr/rotation.php?file=HandBrake-0.10.1-x86_64-Win_GUI.exe

The updated package is awaiting moderation. You can download it directly, by providing a version.

```
choco install handbrake.install -version 0.10.2
```

https://chocolatey.org/packages/handbrake.install/0.10.2
