### ISSUE TITLE
Duplicate helpers in this repo?

### ISSUE THREAD

**Issue by dtgm** [AnthonyMastrean/chocolateypackages#185]
Howdy, I have made mod notes to transition to [internal choco helpers](https://github.com/chocolatey/choco/tree/master/src/chocolatey.resources/helpers/functions) rather than including [helpers in this repo](https://github.com/AnthonyMastrean/chocolateypackages/tree/master/helpers) in pertinent packages.

I admit I have not looked what differences there are... is there a difference? At first glance, it looks like they duplicate the internal helper functions and I'm guessing maybe they were created before the internal helpers existed?

I saw you have an uninstall helper and I proposed using an extension ([chocolatey-uninstall.extension](https://chocolatey.org/packages/chocolatey-uninstall.extension)) for this as noted in  https://github.com/chocolatey/choco/issues/739 and https://github.com/chocolatey/chocolatey-coreteampackages/issues/214. I would welcome including additional helpers in that extension.

One reason I ask is because it takes time looking over the included helpers every time during moderation.

**Comment by dtgm** [comment]
Ok, I actually looked this time :)

### shortcut.ps1
1. [function Install-Shortcut](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/helpers/shortcut.ps1#L89) == https://github.com/chocolatey/choco/blob/master/src/chocolatey.resources/helpers/functions/Install-ChocolateyShortcut.ps1?
2. new [function Uninstall-Shortcut](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/helpers/shortcut.ps1#L134)
3. new [function Resolve-ShortcutLink](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/helpers/shortcut.ps1#L149)

### bins.ps1
1. [function Install-IgnoreBin](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/helpers/bins.ps1#L41)
2. [function Install-GuiBin](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/helpers/bins.ps1#L98) 

### uninstall.ps1
* deprecated by https://chocolatey.org/packages/chocolatey-uninstall.extension

So it looks like these functions are unique: shortcut.ps1 2 and 3 and bins.ps1 1 and 2. Maybe we could add those to a `chocolatey-install.extension`? I need to look at the implications to this as noted in https://github.com/chocolatey/choco/issues/739, but that may make it more manageable and usable by many packages.

**Comment by AnthonyMastrean** [comment]
Thanks for digging in and doing the analysis. I'll read up on the new extensions and some of the pre-existing helpers (I recall not being satisfied with Install-Shortcut).

**Comment by dtgm** [comment]
1. Does `Install-ChocolateyShortcut` deprecate your `Install-Shortcut`?

2. I think we should look at moving your helpers into https://github.com/chocolatey/chocolatey-coreteampackages/tree/master/extensions. Just for ease of management and awareness, ya know?

3. `chocolatey-uninstall.extension` includes the `Get-UninstallRegistryKey` so it is similar to your function, but does not return the UninstallString. I wanted to keep it more versatile for use with the chocolatey template generated with `choco new foo`. I was planning on adding another helper to handle processing the UninstallString properly. More importantly though, that function includes proper handling of bad registry keys which is really, really bad.

**Comment by AnthonyMastrean** [comment]
New and updated packages have been submitted using built-ins and extensions. Thanks :)
