### ISSUE TITLE
cheatengine hash changed

### ISSUE THREAD

**Issue by AnthonyMastrean** [AnthonyMastrean/chocolateypackages#186]
User roncli sends the following message to the maintainers of Package 'cheatengine'.

> I cannot seem to install cheatengine. Here is the details:
> 
> ```
Error - hashes do not match. Actual value was 'E5034FEADC8D2F3B11FE119FC19611DA97C06D1FFD76BBA70895479E378A7907'.
Checksum for 'C:\Users\Ronald\AppData\Local\Temp\chocolatey\cheatengine\6.5.1\c
heatengineInstall.EXE' did not meet
'DD1EA29D5AA8AB75715F8EE07DB9B4C378C41F5B4ED337CDE7B050E4EB3BBEFC' for
checksum type 'SHA256'.
At C:\ProgramData\chocolatey\helpers\functions\Get-CheckSumValid.ps1:59 char:5
+ throw "Checksum for '$file' did not meet '$checksum' for chec ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : OperationStopped: (Checksum for 'C... type 'SHA2 
56'.:String) [], RuntimeException
+ FullyQualifiedErrorId : Checksum for 'C:\Users\Ronald\AppData\Local\Temp 
\chocolatey\cheatengine\6.5.1\cheatengineInstall.EXE' did not meet 'DD1EA2 
9D5AA8AB75715F8EE07DB9B4C378C41F5B4ED337CDE7B050E4EB3BBEFC' for checksum t 
ype 'SHA256'.
The install of cheatengine was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\cheatengine\tools\chocolateyInstall.ps1'.
See log for details.
> 
> Chocolatey installed 0/1 package(s). 1 package(s) failed.
> See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> Failures:
> - cheatengine
> ```
> 
> Package Url: https://chocolatey.org/packages/cheatengine

**Comment by AnthonyMastrean** [comment]
The github release says it was published 13 days ago. 

https://github.com/cheat-engine/cheat-engine/releases

**Comment by 9numbernine9** [comment]
Curiously, I'm having the same problem as reported by roncli. Regardless of how I download the executable, the SHA256 sum of the file is always `74f96ada4a956be76d44b2a357c5b0065c90129aa31d6655f87fc37ef5ecc21c`. 

Things I've tried:
- Letting Chocolatey download the file and running sha256sum (via Cygwin) against the downloaded file.
- Downloading the file manually in both Chrome and Firefox and evaluating the result.
- Downloading on a Mac and running `shasum -a256` against the downloaded file.
- Downloading on a Linux VM and running `sha256sum` against the file. 

There are [VirusTotal results](https://www.virustotal.com/en/file/74f96ada4a956be76d44b2a357c5b0065c90129aa31d6655f87fc37ef5ecc21c/analysis/) for this hash, and they are very similar to the ones for the hash you linked in your comment.

Thoughts? :-)

**Comment by AnthonyMastrean** [comment]
Seems like I have to publish an update with this new hash... love to know how/why it changed :(
