### ISSUE TITLE
Update clink to v0.4.8

### ISSUE THREAD

**Issue by koppor** [AnthonyMastrean/chocolateypackages#208]
Is it possible to update clink to the most recent version?

Refs https://github.com/mridgers/clink/issues/276

**Comment by AnthonyMastrean** [comment]
I am no longer maintaining this package.

**Comment by koppor** [comment]
On https://chocolatey.org/packages/clink, the link "Package Source" points to https://github.com/AnthonyMastrean/chocolateypackages/

I assume that someone else has to take over maintenance and afterwards, the link on chocolatey will be fixed.
