### ISSUE TITLE
sqljdbc times out

### ISSUE THREAD

**Issue by pinterl** [AnthonyMastrean/chocolateypackages#219]
In the Chef script the following resource just times out every time.

chocolatey_package 'sqljdbc' do
options "--allow-empty-checksums --ignore-package-exit-codes"
timeout 3600
End

When I execute the choco install command on the box, a popup window comes up. Most likely the installer is waiting for Chef to click the button on the window.
We use this great package, please help us to make it work again.
![image](https://cloud.githubusercontent.com/assets/12851573/22132852/6c571e86-de71-11e6-9420-3da15af6495e.png)

**Comment by dragon788** [comment]
According to the code it should be auto extracting in the background to a specific folder. https://github.com/AnthonyMastrean/chocolateypackages/blob/master/packages/sqljdbc/tools/chocolateyInstall.ps1

Do you have the chocolatey.log from your chef and manual install attempts in a gist somewhere?

**Comment by Nia-UMG** [comment]
Hi there,

Attached is a file with the logs from chocolatey.log related to SQLJDBC.
[chocolatey.txt](https://github.com/AnthonyMastrean/chocolateypackages/files/720282/chocolatey.txt)

Thanks, Nia

**Comment by dragon788** [comment]
What version of Windows are you installing this on? I see you have PowerShell 2.0 or maybe 3.0? `$PSVersionTable` should list that out for you.

**Comment by pinterl** [comment]
Windows Server 2012R2

Thank you,

Laszlo Pinter $B("(BSenior DevOps Engineer, Digital Initiatives and Global Digital Supply Chain$B("(BUniversal Music Group, Global IT
21301 Burbank Blvd, 3B-082A $B("(B Woodland Hills, CA $B("(B 91367
office phone: 818.286.6618 | email: laszlo.pinter@umusic.com<mailto:laszlo.pinter@umusic.com>

**Comment by AnthonyMastrean** [comment]
The Microsoft team revoked the previous artifact when they published the latest one, so the URL disappeared. New package is up.

**Comment by Nia-UMG** [comment]
Hi Anthony,

When we use choco download, we get chocolateyInstall.ps1 code and the URL to download the SQLJDBC: http://download.microsoft.com/download/0/2/A/02AAE597-3865-456C-AE7F-613F99F850A8/sqljdbc_4.0.2206.100_enu.exe 

This is the error message:

This site can’t be reached
The webpage at http://download.microsoft.com/download/0/2/A/02AAE597-3865-456C-AE7F-613F99F850A8/sqljdbc_4.0.2206.100_enu.exe might be temporarily down or it may have moved permanently to a new web address.

Please advise,
Nia

**Comment by AnthonyMastrean** [comment]
The update is making its way through moderation.

https://chocolatey.org/packages/sqljdbc/6.0.8112.100

You can install it right now, by providing the exact version.

```
choco install sqljdbc -version 6.0.8112.100
```

**Comment by Nia-UMG** [comment]
Hi Anthony,
I will try that but we have a license for chocolatey and we are trying to internalize all the packages. In order to do that, we need to be able to download the executable.
Nia

**Comment by Nia-UMG** [comment]
Hi Anthony, it doesnt work... Please look at the attachment.
![sqljdbc](https://cloud.githubusercontent.com/assets/6546973/22436041/4b239f0a-e6d7-11e6-8383-41e0a83e5f59.png)

**Comment by AnthonyMastrean** [comment]
It works reliably on my test VM, even running it several times in a row. I can't really support you any further, sorry. If you can find a set of silent install flags that works, please recommend them. The Microsoft team that produces this application provides it this way, we have to work with what they provide.

You could always create a new package and host that internally. Unzip the content manually and put it in a regular ZIP file or something? Then you could use `Install-ChocolateyZipPackage` instead of what I'm doing.

**Comment by ferventcoder** [comment]
Howdy folks - please remember that packages on the community repository are not supported.

There are options here however. You can contact the Chocolatey support team about purchasing professional packaging services to create an unattended package for SQLJDBC installation if you are a customer. Packaging services are fixed cost on pricing and a pretty good deal when things like Package Internalizer and Package Builder are not able to handle ensuring unattended installation. Typically in about 10% of the cases you run into things like this, where nothing really wants to work in a silent manner.  HTH
