### ISSUE TITLE
goggalaxy moderation comments

### ISSUE THREAD

**Issue by AnthonyMastrean** [AnthonyMastrean/chocolateypackages#229]
@Natrezim I received the following comments on `goggalaxy` last time I submitted. I did not address these issues. Can you take a look?

 - [x] Add dependency on [kb2919355](https://chocolatey.org/packages/KB2919355). This package only runs on Windows 8 & 8.1 and Windows Server 2012 R2. This will enable the package to pass automated tests, but it won't screw up your Windows 10 machine, for example.
 - [x] Add `admin` tag to the [nuspec](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/packages/goggalaxy/goggalaxy.nuspec#L14).
 - [x] Set minimum version for dependencies in the [nuspec](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/packages/goggalaxy/goggalaxy.nuspec#L22) (like, `version="[1.0,)"`, which means `>= 1.0`).

```
'goggalaxy' is Submitted.
Current status = Waiting for Maintainer to take corrective action

AdmiringWorm left the following comment(s):

It actually hangs/fails because you are missing a dependency on kb2919355.
Please add that dependency, and if the testing fails then request an exemption (it may fail because kb2919355 requires a reboot to be completely installed).

while you're at it, please add the admin tag and a minimum version for the dependencies.

Thanks,
Kim
```

**Comment by Natrezim** [comment]
Hi @AnthonyMastrean,
I will look on these issues. Is there any way to test the package installation before sending a pull request?

**Comment by AnthonyMastrean** [comment]
I have a `Vagrantfile` defined that should boot up a box very similar to the Windows Server 2012 R2 box that is used during automated checks. You can install VirtualBox and Vagrant.

```
PS> choco install -y virtualbox vagrant
```

Then boot up the box (make sure you're at the root of the workspace for this repository).

```
PS> vagrant up
```

It should spent a ton of time downloading the box image (it's a couple of GBs). It will take a little while to configure the box the first time, after that, it should use very fast snapshots.

You can open a PowerShell Window in the guest VM and use a helper script...

```
PS> cd C:\vagrant
PS> .\install.ps1 goggalaxy
```

**Comment by AnthonyMastrean** [comment]
It looks like GOG released another update, too. You can tackle this as well, if you're still interested :)

 * Version: `1.2.9.5`
 * URL: `https://cdn.gog.com/open/galaxy/client/setup_galaxy_1.2.9.5.exe`
 * Checksum: `156823CF8B540D370ADC6F5F93548FFF5A33053A5101EAE275D00133EE347E5E`

I get checksums using PowerShell.

```
PS> Get-FileHash .\setup_galaxy_1.2.9.5.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          156823CF8B540D370ADC6F5F93548FFF5A33053A5101EAE275D00133EE347E5E       .\setup_galaxy_1.2.9.5.exe
```

**Comment by AnthonyMastrean** [comment]
Sorry for the long delay getting back to you. I was busy with a new job and I got frustrated with some moderation drama on Chocolatey.
