### ISSUE TITLE
update the jdbc package to 6.2.1

### ISSUE THREAD

**Issue by rgl** [AnthonyMastrean/chocolateypackages#242]
6.2.1 is available at https://www.microsoft.com/en-us/download/details.aspx?id=55539 (which is referenced from https://docs.microsoft.com/en-us/sql/connect/sql-connection-libraries#anchor-20-drivers-relational-access)

**Comment by AnthonyMastrean** [comment]
Thanks for the heads up, but I'm not actively using this package any more. I have a lot on my plate right now... Would you like to try to update the package and send me a PR? Should be just a couple of updates (link, checksum, version).

**Comment by BarnumD** [comment]
I've just pushed a request for 7.0.0.0 in Merge request #292 / Issue #291.
