### ISSUE TITLE
No Shims created for notepad2

### ISSUE THREAD

**Issue by cmorty** [AnthonyMastrean/chocolateypackages#243]
No shims are created for notepad2. I'm however not sure whether this is a chocolatey or packaging issue.

**Comment by AnthonyMastrean** [comment]
Notepad2 "takes over" your Windows OS `notepad.exe` somehow. Just launch Notepad like normal and watch!

**Comment by cmorty** [comment]
Ok, maybe this should be added to the documentation. Do you want a PR (I'd also refactor the Discription to make it more generic)?

**Comment by AnthonyMastrean** [comment]
Sure, a PR would be awesome, thank you!
