### ISSUE TITLE
rsync: check for `ssh` in the path before creating shims

### ISSUE THREAD

**Issue by AnthonyMastrean** [AnthonyMastrean/chocolateypackages#249]
I've not personally encountered this problem. I wrote it up in response to a package comment or email or something... I don't really have many details. May reopen if I get enough pressure from actual users w/ this issue 😄

**Comment by paladinshiva** [comment]
If ((Test-Path $TargetFolder) -AND (@(dir "$TargetFolder\*.exe").count -gt 0)) 
{
  Write-Output "`r`nCURRENT VERSIONS OF SSH EXES:"
    Write-Output "$(dir "$TargetFolder\*.exe"| select -expand fullname | get-command | select -expand fileversioninfo | ft filename, fileversion -auto | out-string)"
}

**Comment by AnthonyMastrean** [comment]
I've not personally encountered this problem. I wrote it up in response to a package comment or email or something. I didn't really get too much info. @paladinshiva do you have this issue? Can you provide more details?

**Comment by paladinshiva** [comment]
Oh, sorry man... I've thought you wanted to how it'd look like. I don't have the issue either...

**Comment by AnthonyMastrean** [comment]
No problem! It's a good start... I'm only just starting to experiment with Microsoft's OpenSSH, so maybe I'll feel like fixing this soon 😉
