### ISSUE TITLE
Update sqljdbc

### ISSUE THREAD

**Issue by rgl** [AnthonyMastrean/chocolateypackages#262]
Can you please update the sqljdbc package? The newer version (6.2.2.0) is available at https://docs.microsoft.com/en-us/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server or more exactly at https://www.microsoft.com/en-us/download/details.aspx?id=55539.

**Comment by AnthonyMastrean** [comment]
https://chocolatey.org/packages/sqljdbc/6.2.2.0
