### ISSUE TITLE
Rsync Package Broke.

### ISSUE THREAD

**Issue by m-nathani** [AnthonyMastrean/chocolateypackages#275]
Getting Not Found on the requested URL 'https://www.itefix.net/dl/cwRsync_5.5.0_x86_Free.zip' was not found on this server.

Please update the package, as the rsync package on itefix is updated to 'https://itefix.net/dl/cwrsync_5.7.1_x86_free.zip'

Please review and merge https://github.com/AnthonyMastrean/chocolateypackages/pull/274

**Comment by AnthonyMastrean** [comment]
Duplicates #279
