### ISSUE TITLE
Rsync package now requires a "download fee"

### ISSUE THREAD

**Issue by calsirlerilor** [AnthonyMastrean/chocolateypackages#279]
itefix updated cwrsync again and removed the binary version 5.7.1.

However, they added a "download fee": https://www.itefix.net/content/cwrsync-free-edition

This time we need a separate repository to distribute the binary, as they are freely redistributable: https://web.archive.org/web/20180524124542/https://www.itefix.net/cwrsync?qt-cwrsync=5 (I archived the page just in case).

Best regards,

-- 
Carlo

**Comment by AnthonyMastrean** [comment]
These folks are _not happy_ about hosting this file 😁

**Comment by calsirlerilor** [comment]
Indeed.
This is why the binaries should be hosted elsewhere. According to their own license page this is allowed, and I do not see reasons we should not do it.

-- 
Carlo

**Comment by AnthonyMastrean** [comment]
For now, I've uploaded this update to the previous version.

https://chocolatey.org/packages/rsync/5.5.0.20180530

I'm going to contact the vendor and see if they'll send me the binaries when they publish updates to avoid the $6/download on every new version 😄

**Comment by AnthonyMastrean** [comment]
I emailed the vendor:

> Anthony Mastrean (anthony.mastrean@gmail.com) sent a message using the contact form at
> https://www.itefix.net/contact.
> 
> I'm the maintainer of the cwRsync package on Chocolatey.org (it's an application package manager
> for Windows): https://chocolatey.org/packages/rsync
> 
> I understand your issue with "free" downloads and the institution of the fee-per-download. I was
> wondering if we could work together to find a platform to host your binary so I could continue
> maintaining this package (otherwise, we're stuck at 5.5.0, currently pointing to archive.org).

They responded: 

> Hi Anthony,
> 
> It is actually to fire up a Cygwin environment, extract binaries, dependent DLLs and pack them into a zip Archive and call it what you want (I've used cwRsync :-)). That's all you need for a client functionality. IMHO, v5.5.0 is just fine.
> 
> I see that your chocolatey has gone commercial too. I have no problems with to understand that - If you want to offer software with support and quality, you need to charge some way.
> 
> Kind regards
> Tev

I'll take that as a "No" 🤷‍♀️

**Comment by Noiwex** [comment]
![](https://i.imgur.com/oSp0Uis.png)

umm, is this normal?
