### ISSUE TITLE
Liquibase > Upgrade 3.6.1 -> 3.6.2

### ISSUE THREAD

**Issue by adriens** [AnthonyMastrean/chocolateypackages#305]
https://www.liquibase.org/2018/06/liquibase-3-6-2-released.html

**Comment by AnthonyMastrean** [comment]
@adriens the [Liquibase package](https://github.com/AnthonyMastrean/chocolateypackages/tree/master/packages/liquibase) is _really_ easy to update if you want to send a PR 😄 

 * Update [the version](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/packages/liquibase/liquibase.nuspec#L6). Then any other version related URLs in the nuspec file. It looks like the release notes URL might need an update... although now I see that they maintain slightly different release notes on [the blog](https://www.liquibase.org/2018/06/liquibase-3-6-2-released.html) and on [the github page](https://github.com/liquibase/liquibase/releases/tag/liquibase-parent-3.6.2).
 * Find the new `.zip` URL on that same github release page and update the [install script](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/packages/liquibase/tools/chocolateyInstall.ps1#L5-L10). Update the checksum (`Get-FileHash`, in PowerShell).

**Comment by adriens** [comment]
I've asked Liquibase team to add checksum too to their releases see https://liquibase.jira.com/browse/CORE-3364

**Comment by adriens** [comment]
I'm on it, don'ti do it, I'll PR you today ! 🎁

**Comment by adriens** [comment]
Here it is 👏

**Comment by adriens** [comment]
Ihave upgraded Java runtime to `>8.0`, please le me know if you're 👍  with that.

**Comment by adriens** [comment]
Wait until #320 is fixed @AnthonyMastrean

**Comment by adriens** [comment]
Can you please add me to the package maintainers #321 @AnthonyMastrean  ?
