### ISSUE TITLE
Liquibase > Add me to the package maintainers

### ISSUE THREAD

**Issue by adriens** [AnthonyMastrean/chocolateypackages#321]
Could you please add me, [adriens](https://chocolatey.org/profiles/adriens) to the maintainers ? I have some ideas to improve the package, if you're ok with that, and to do my best to keep it up to date... and make the choco experience the best for liquibase Windows install process.

**Comment by AnthonyMastrean** [comment]
@sales I'm mostly back to work now. Mama and baby are doing great, thanks for being patient! I think you should just take over the entire liquibase package (source code and all). I'm not responding rapidly enough these days. And I'm not ready to merge auto-package-updating into my repo yet 😅.

Make a new personal chocolateypackages project (not just a fork of mine, it'll be easier that way). Copy the liquibase package folder and files and feel free to maintain them however you like.

I'll make you the sole maintainer of the package and, since I'm a moderator, I can make sure that it gets approved rapidly. Please update the owners, packageSourceUrl, and iconUrl.

**Comment by adriens** [comment]
Great news for your family.
For the repo, I'll do so, thank you :+1:

**Comment by AnthonyMastrean** [comment]
Let me know when you're up and running and I'll remove my files 🥳

**Comment by adriens** [comment]
Yep, hopefully this week-end :+1:

**Comment by adriens** [comment]
Hi, I could locally prepare my package,on `3.6.3`. 
Sorry for the question but the release process is not that clear for me :

- Shall I push releases straght to choco repo...and you'll drop liquibase directory in your sources ?
- Should I push files on you GH repo then you release it ?

If the second option, let me know, I'll configure automatic release from Appveyor

**Comment by AnthonyMastrean** [comment]
Looks great! So, you'll just update your project. I'll remove the files from mine. You can manually build or take the nupkg from your appveyor build and use

```
PS> choco push liquibase###.nupkg
```

**Comment by AnthonyMastrean** [comment]
Looks like you still need to accept maintainership of the liquibase package (might be stuck in your email)? When that's done you can _remove_ me from the list... https://chocolatey.org/packages/liquibase/ManagePackageOwners

**Comment by AnthonyMastrean** [comment]
https://github.com/AnthonyMastrean/chocolateypackages/commit/ba1a10ea2999c430bdc621587ac7b08299bbe0e6

**Comment by adriens** [comment]
https://ci.appveyor.com/project/adriens/chocolatey-liquibase

![2019-02-17 08_57_10-chocolatey gallery _ liquibase 3 6 1](https://user-images.githubusercontent.com/5235127/52905714-1a567b00-3292-11e9-8c7c-44c327a69bf6.png)

**Comment by adriens** [comment]
Now waiting for moderation...

**Comment by adriens** [comment]
I guess the new nuspec will be taken in account while the new package will be accepted

![2019-02-17 08_59_11-chocolatey gallery _ liquibase 3 6 1](https://user-images.githubusercontent.com/5235127/52905730-71f4e680-3292-11e9-8919-016ee7e49951.png)

**Comment by adriens** [comment]
I wait for the whole process to be ended before closing this issue, you're ok with that.

**Comment by adriens** [comment]
Here we go @AnthonyMastrean  👏  😄 

![2019-02-17 10_56_22-chocolatey gallery _ liquibase 3 6 3](https://user-images.githubusercontent.com/5235127/52906575-cbfda800-32a2-11e9-8d9c-288bc1d3d6dd.png)

**Comment by adriens** [comment]
Running a scratch test on a local machine...

**Comment by adriens** [comment]
Looks good 👍

**Comment by AnthonyMastrean** [comment]
Thank you!

**Comment by adriens** [comment]
Thank you to you. Do you have any linkedIn page ?

**Comment by AnthonyMastrean** [comment]
Nope ;)
