### ISSUE TITLE
multiple rsync processes running

### ISSUE THREAD

**Issue by AnthonyMastrean** [AnthonyMastrean/chocolateypackages#325]
![](https://i.imgur.com/oSp0Uis.png)

umm, is this normal?

_Originally posted by @Noiwex in https://github.com/AnthonyMastrean/chocolateypackages/issues/279#issuecomment-453002889_

**Comment by Noiwex** [comment]
I've just tried running rsync but it just hangs there with no output. Blank options, --help, --?, -?, nothing works, it just replicates itself.

**Comment by AnthonyMastrean** [comment]
Cannot repro, sorry. Please reopen if you ever get more info.
