### ISSUE TITLE
Add NetHack classic to path

### ISSUE THREAD

**Issue by cybercatgurrl** [AnthonyMastrean/chocolateypackages#347]
After installing nethack I was unable to run it from my terminal without adding it to the PATH. I think it should automatically do this.

**Comment by AnthonyMastrean** [comment]
Yeah, I can add this! I think I had avoided it previously because the Windows console actually launched this as a separate process/window instead of running it in the current session. But, it looks like either A) I was wrong all along 😄 or B) the recent Windows console improvements are helping.

**Comment by AnthonyMastrean** [comment]
I do also add most of my UI packages to your Start Menu.

![image](https://user-images.githubusercontent.com/217842/59104568-e914c000-88ff-11e9-8b01-9598353b4d19.png)

**Comment by AnthonyMastrean** [comment]
Fixed b4633443248321672349ad1eb5c81f575c624f04
