### ISSUE TITLE
rsync ssh keys directory

### ISSUE THREAD

**Issue by kleo** [AnthonyMastrean/chocolateypackages#360]
rsync looks for ssh keys at /home/.ssh/ instead of /c/Users/username on Windows 10 Git Bash.  Also not working when manually specifying directory using rsync -e 'ssh -i /c/Users/username'

**Comment by AnthonyMastrean** [comment]
This rsync is a Windows port. It’s not cross-platform. That said, there’s no expectation that it will work in Git Bash (which ships all of it’s own executables).
