### ISSUE TITLE
shellcheck bump to 0.7.0

### ISSUE THREAD

**Issue by PAStheLoD** [AnthonyMastrean/chocolateypackages#365]
Hello,

I hope this is the correct way to request a package update.

First of all thanks for packaging/maintaining the shellcheck choco package, it's really helpful.

So, there's a 0.7.0 release of shellcheck since July 29, it'd be good to update the installer script.

Thanks!

**Comment by AnthonyMastrean** [comment]
@PAStheLoD thanks! There's a "Contact Maintainers" link on every package page that also works (it actually sends an email to *each* maintainer separately, which is sometimes helpful).

https://www.chocolatey.org/packages/shellcheck/ContactOwners

**Comment by AnthonyMastrean** [comment]
Pending review!

https://www.chocolatey.org/packages/shellcheck/0.7.0

**Comment by PAStheLoD** [comment]
Wow, that was fast! Thanks again!

I wanted to send a pull request, but wasn't sure how to test it, and then though it's better to just raise the issue.

**Comment by AnthonyMastrean** [comment]
Yeah, every maintainer is a little different. Best to start with the contact link, then escalate to an issue or PR. 

One of these days, I’ll get around to setting up automatic packages!
