### ISSUE TITLE
Can we maintain one JDK package?

### ISSUE THREAD

**Issue by AnthonyMastrean** [AnthonyMastrean/chocolateypackages#51]
There are a handful of JDK packages on Chocolatey and I think they're all [out of date](https://twitter.com/jimevansmusic/status/458640121181794305): [jdk](http://chocolatey.org/packages/jdk), [jdk7](http://chocolatey.org/packages/jdk7), [jdk8](http://chocolatey.org/packages/jdk8), [java.jdk](http://chocolatey.org/packages/java.jdk)

The JDK download is [notoriously](https://github.com/carolynvs/chocolatey-packages/blob/master/Java.JDK/tools/chocolateyInstall.ps1) [hard](https://github.com/Iristyle/ChocolateyPackages/blob/master/JDK7/tools/chocolateyInstall.ps1) to [script](https://github.com/AnthonyMastrean/chocolateypackages/blob/master/packages/jdk/tools/chocolateyInstall.ps1) (compared to your usual chocolatey package) because it's behind a license acceptance button. You have to setup some cookies and write your own downloader.

``` powershell
  [System.Net.ServicePointManager]::ServerCertificateValidationCallback = { $true }
  $client = New-Object "System.Net.WebClient"
  $client.Headers.Add("Cookie", "gpw_e24=http://www.oracle.com")
  $client.DownloadFile($dl, $temp)
```

This loses you a lot of the built-in Chocolatey features:
- installer parameters (like a non-default `INSTALLDIR`)
- download progress
- installing specific package architectures (using the `-x86` flag to force the x86 package)

Then, there's a number of things that you can try to do to be "helpful" because the JDK installer doesn't do it automatically. I don't know which of these is desirable or what edge cases there are (taking into account multiple installed JDKs/JREs, manual customziations in your environment, etc)
- set the `JAVA_HOME` environment variable
- set a default `CLASSPATH` environment variable
- put the `<install-dir>\Java\bin` directory on the environment `PATH`

Now, assuming we hammer out the technical implementation details and figure out how to support all of the Chocolatey features (look at [PR-171](https://github.com/chocolatey/chocolatey/pull/171) for a possible reprieve), we need to talk about how best to name/version this thing.

We already know that the JDK is named/versioned like crazy

![image](https://cloud.githubusercontent.com/assets/217842/2771044/fdb2be80-ca65-11e3-851b-6ace95d6c49c.png)

So, version "7" in the name is mapped to the minor version segment and the update "45" is in a magical 4th version segment that's not supported by [semver](http://semver.org/)/[nuget](https://docs.nuget.org/docs/Reference/Versioning) at all. They fix that in version 8. But, the update number is given an extra order of magnitude in both cases, from 45 to 450 and 5 to 50, great!

It seems "normal" in the Java ecosystem, and probably stable enough for many years, to remap this onto one package/version scheme. But, we should take into account installing multiple JDKs, side-by-side. We may want to release packages like this...

| id | version |
| --- | --- |
| jdk7 | 7.0.45 |
| jdk8 | 8.0.5 |

Lots of comments [here](http://chocolatey.org/packages/javaruntime#comment-1161416310) and [here](https://github.com/chocolatey/chocolatey/wiki/CreatePackages#naming-your-package) on naming.

---

//cc @carolynvs @adorepump @iristyle @ootaken @digitaldrummerj

**Comment by alangibson** [comment]
Brilliant idea. Is this getting any traction? 

I've run into the issue that the java.jdk package does not use Get-WebFile, which means it does not work from behind a proxy that requires auth. This is however mostly chocolatey's fault since Get-WebFile doesn't support adding headers, which is needed by that code block you posted.

FWIW, I created this issue right before I found this post:

    https://github.com/carolynvs/chocolatey-packages/issues/3

**Comment by carolynvs** [comment]
I would love to see the various packages consolidated. Once [PR 171](https://github.com/chocolatey/chocolatey/pull/171) is merged and released, it should greatly simplify the implementation.

**Comment by AnthonyMastrean** [comment]
FYI, I'm not sure why so many JDK packages are more complicated than this:

https://github.com/AnthonyMastrean/chocolateypackages/blob/master/packages/jdk/tools/chocolateyInstall.ps1

**Comment by digitaldrummerj** [comment]
I am all for combining the JDK 7 packages but is it even worth it since Oracle has a note on the download site that the April 2015 CPU release will be the last publicly available update? For JDK 8 there appears to only be one package in the Chocolatey Gallery.

JDK 7 download site: http://www.oracle.com/technetwork/java/javase/downloads/jdk7-downloads-1880260.html

**Comment by AnthonyMastrean** [comment]
Haha, we accidentally waited out the software :stuck_out_tongue_closed_eyes:

**Comment by carolynvs** [comment]
I was asked by the Chocolatey maintainers to deprecate java.jdk. I plan on doing that this weekend. So there will be one less variation to deal with. :)

**Comment by digitaldrummerj** [comment]
Fyi - I also submitted an update to the JDK 7 package to update it to the .76 release of the JDK.
